#!/usr/bin/env python3
hosts = {
	"keeton": "keeton"
}
import os, sys, subprocess

with open("/etc/hostname", "r") as f:
        lh = f.read().replace("\n", "")

def depl(to):
	os.system("sudo nix-channel --update")
	to = [t for t in to if t in hosts.keys()]
	for host in to:
		os.system(f"nixos-rebuild --target-host rsk@{hosts[host]} --use-remote-sudo -I nixos-config=/etc/nixos/{host}.nix switch")



if len(sys.argv) > 1:
	depl(sys.argv[1:])
else:
	depl([lh])
