#!/usr/bin/env python3

dots = {
    ".bashrc": None,
    ".bash_profile": None,
    ".Xresources": None,
    ".ssh/config": "ssh_config",
    ".config/i3/config": "i3-config",
    ".config/i3blocks/config": "i3blocks/config",
    ".config/i3blocks/memory": "i3blocks/config",
    ".config/i3blocks/cpu_usage": "i3blocks/config",
    ".config/i3blocks/iface": "i3blocks/config",
    ".mozilla/firefox/profiles.ini": "ff/profiles.ini",
    ".mozilla/firefox/vaex616s.default/user.js": "ff/user.js",

    "data": "/mnt/cistern/home/rsk/data"
}
import os
from sys import exit

base = os.path.dirname(os.path.abspath(__file__)) + "/cfgz/"
for dst in dots.keys():
    src = dst if dots[dst] is None else dots[dst]
    # sources that start with a `/` are assumed to be absolute
    src = base + src if not dst.startswith("/") else src

    dst = "/state/home/rsk/" + dst

    err = ""
    if not os.path.exists(src):
        err = "source does not exist\n"
    if os.path.exists(dst) and not os.path.islink(dst):
        err += "dst already exists, and is NOT a symlink\n"

    if err != "":
        print(src, dst, err)
        exit(1)
    
    bld = "/".join(dst.split("/")[:-1])
    if "/" in dst and not os.path.exists(bld):
        print(f"securing the existence of our dirs and a future for {dst} symlinks")
        os.system("mkdir -p "+bld)
    if os.path.exists(dst):
        print("deleting", dst)
        os.unlink(dst)

    print("linking", src, "to", dst)
    os.symlink(src, dst)
