#!/bin/bash

# create dirs

declare -A dirs=(
    ["/mnt/state"]="0755 root:root"
    ["/mnt/state/home"]="0755 root:root"
    ["/mnt/state/secrets"]="0700 root:root"
)

for d in "${!dirs[@]}"; do
    read -r mode owner <<< "${dirs[$d]}"
    
    echo "fixing $d..."
    mkdir -p "$d"
    chmod "$mode" "$d"
    chown "$owner" "$d"
done

# unpack secrets

touch /dev/shm/keys.txt
chmod 600 /dev/shm/keys.txt
echo "provide secret key" && pause
nano /dev/shm/keys.txt

for f in ./secrets/*.age; do
    filename=$(basename "$f")
    output_name="${filename%.age}"
    
    echo "decrypting $filename..."
    age --decrypt -i /dev/shm/keys.txt -o "/mnt/state/secrets/$output_name" "$f"
done

rm /dev/shm/keys.txt