#!/usr/bin/env bash

# create dirs

declare -A dirs=(
    ["/mnt/state"]="0755 root:root"
    ["/mnt/state/home"]="0755 root:root"
    ["/mnt/state/secrets"]="0700 root:root"
)

for d in "${!dirs[@]}"; do
    read -r mode owner <<< "${dirs[$d]}"
    
    echo "fixing $d..."
    mkdir -p "$d"
    chmod "$mode" "$d"
    chown "$owner" "$d"
done

# unpack secrets

for f in ./secrets/*.age; do
    filename=$(basename "$f")
    output_name="${filename%.age}"
    
    echo "decrypting $filename..."
    age --decrypt -o "/mnt/state/secrets/$output_name" "$f"
    chmod 600 "/mnt/state/secrets/$output_name"
done

# clone repo for later use

git clone https://github.com/kurisufriend/construct /mnt/state/construct

# gen initial cfg

nixos-generate-config --root /mnt

# useless fucking comments
sed -i '/^\s*#/d' /mnt/etc/nixos/configuration.nix
sed -i '/^\s*$/d' /mnt/etc/nixos/configuration.nix

## this will be in override.nix
sed -i '/^\s*boot.loader.*$/d' /mnt/etc/nixos/configuration.nix
